FROM robocomp/robocomp:focal_dev

# LABEL about the custom image
LABEL maintainer="emartinena@unex.es"
LABEL version="0.1"
LABEL description="This is custom Docker Image for Robocomp in Ubuntu Focal"

# Disable Prompt During Packages Installation
ARG DEBIAN_FRONTEND=noninteractive

USER root
RUN apt update && apt-get install --no-install-recommends --yes \
  libfcl-dev
USER robolab
RUN cd /home/robolab/robocomp && mkdir -p build && cd build && cmake -DFCL_SUPPORT=True .. && make -j$(nproc)
USER root
RUN cd /home/robolab/robocomp/build && make install
USER robolab

#  docker build -f Dockerfile.dev -t robocomp/robocomp:focal_fcl_dev .
