// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Test.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ____Test_h__
#define ____Test_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace RoboCompTests
{

class test;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompTests::test>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompTests::test*);

class serviceTest;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompTests::serviceTest>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompTests::serviceTest*);

class publishTest;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompTests::publishTest>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompTests::publishTest*);

}

}

namespace RoboCompTests
{

class test;
bool operator==(const test&, const test&);
bool operator<(const test&, const test&);
::Ice::Object* upCast(::RoboCompTests::test*);
typedef ::IceInternal::Handle< ::RoboCompTests::test> testPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompTests::test> testPrx;
void __patch(testPtr&, const ::Ice::ObjectPtr&);

class serviceTest;
bool operator==(const serviceTest&, const serviceTest&);
bool operator<(const serviceTest&, const serviceTest&);
::Ice::Object* upCast(::RoboCompTests::serviceTest*);
typedef ::IceInternal::Handle< ::RoboCompTests::serviceTest> serviceTestPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompTests::serviceTest> serviceTestPrx;
void __patch(serviceTestPtr&, const ::Ice::ObjectPtr&);

class publishTest;
bool operator==(const publishTest&, const publishTest&);
bool operator<(const publishTest&, const publishTest&);
::Ice::Object* upCast(::RoboCompTests::publishTest*);
typedef ::IceInternal::Handle< ::RoboCompTests::publishTest> publishTestPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompTests::publishTest> publishTestPrx;
void __patch(publishTestPtr&, const ::Ice::ObjectPtr&);

}

namespace RoboCompTests
{

class Callback_test_printmsg_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_test_printmsg_Base> Callback_test_printmsgPtr;

class Callback_serviceTest_srvTest_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_serviceTest_srvTest_Base> Callback_serviceTest_srvTestPtr;

class Callback_publishTest_msgTest_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_publishTest_msgTest_Base> Callback_publishTest_msgTestPtr;

}

namespace IceProxy
{

namespace RoboCompTests
{

class test : virtual public ::IceProxy::Ice::Object
{
public:

    void printmsg(const ::std::string& message)
    {
        printmsg(message, 0);
    }
    void printmsg(const ::std::string& message, const ::Ice::Context& __ctx)
    {
        printmsg(message, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_printmsg(const ::std::string& message, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_printmsg(message, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_printmsg(const ::std::string& message, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_printmsg(message, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_printmsg(const ::std::string& message, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_printmsg(message, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_printmsg(const ::std::string& message, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_printmsg(message, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_printmsg(const ::std::string& message)
    {
        return begin_printmsg(message, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_printmsg(const ::std::string& message, const ::Ice::Context& __ctx)
    {
        return begin_printmsg(message, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_printmsg(const ::std::string& message, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_printmsg(message, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_printmsg(const ::std::string& message, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_printmsg(message, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_printmsg(const ::std::string& message, const ::RoboCompTests::Callback_test_printmsgPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_printmsg(message, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_printmsg(const ::std::string& message, const ::Ice::Context& __ctx, const ::RoboCompTests::Callback_test_printmsgPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_printmsg(message, &__ctx, __del, __cookie);
    }

    void end_printmsg(const ::Ice::AsyncResultPtr&);
    
private:

    void printmsg(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_printmsg(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<test> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_secure(bool __secure) const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_twoway() const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_oneway() const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_batchOneway() const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_datagram() const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_batchDatagram() const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_compress(bool __compress) const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_timeout(int __timeout) const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<test> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<test*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

class serviceTest : virtual public ::IceProxy::Ice::Object
{
public:

    void srvTest(::Ice::Int id, ::Ice::Int& idTest)
    {
        srvTest(id, idTest, 0);
    }
    void srvTest(::Ice::Int id, ::Ice::Int& idTest, const ::Ice::Context& __ctx)
    {
        srvTest(id, idTest, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_srvTest(::Ice::Int id, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_srvTest(id, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_srvTest(::Ice::Int id, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_srvTest(id, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_srvTest(::Ice::Int id, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_srvTest(id, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_srvTest(::Ice::Int id, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_srvTest(id, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_srvTest(::Ice::Int id, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (::Ice::Int)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::RoboCompTests::serviceTestPrx __proxy = ::RoboCompTests::serviceTestPrx::uncheckedCast(__result->getProxy());
                ::Ice::Int idTest;
                try
                {
                    __proxy->end_srvTest(idTest, __result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(idTest);
                }
            }
        
        private:
            
            ::std::function<void (::Ice::Int)> _response;
        };
        return begin_srvTest(id, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_srvTest(::Ice::Int id)
    {
        return begin_srvTest(id, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_srvTest(::Ice::Int id, const ::Ice::Context& __ctx)
    {
        return begin_srvTest(id, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_srvTest(::Ice::Int id, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_srvTest(id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_srvTest(::Ice::Int id, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_srvTest(id, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_srvTest(::Ice::Int id, const ::RoboCompTests::Callback_serviceTest_srvTestPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_srvTest(id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_srvTest(::Ice::Int id, const ::Ice::Context& __ctx, const ::RoboCompTests::Callback_serviceTest_srvTestPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_srvTest(id, &__ctx, __del, __cookie);
    }

    void end_srvTest(::Ice::Int& idTest, const ::Ice::AsyncResultPtr&);
    
private:

    void srvTest(::Ice::Int, ::Ice::Int&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_srvTest(::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<serviceTest> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_secure(bool __secure) const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_twoway() const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_oneway() const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_batchOneway() const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_datagram() const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_batchDatagram() const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_compress(bool __compress) const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_timeout(int __timeout) const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<serviceTest> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<serviceTest*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

class publishTest : virtual public ::IceProxy::Ice::Object
{
public:

    void msgTest(::Ice::Int id)
    {
        msgTest(id, 0);
    }
    void msgTest(::Ice::Int id, const ::Ice::Context& __ctx)
    {
        msgTest(id, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_msgTest(::Ice::Int id, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_msgTest(id, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_msgTest(::Ice::Int id, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_msgTest(id, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_msgTest(::Ice::Int id, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_msgTest(id, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_msgTest(::Ice::Int id, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_msgTest(id, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_msgTest(::Ice::Int id)
    {
        return begin_msgTest(id, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_msgTest(::Ice::Int id, const ::Ice::Context& __ctx)
    {
        return begin_msgTest(id, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_msgTest(::Ice::Int id, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_msgTest(id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_msgTest(::Ice::Int id, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_msgTest(id, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_msgTest(::Ice::Int id, const ::RoboCompTests::Callback_publishTest_msgTestPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_msgTest(id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_msgTest(::Ice::Int id, const ::Ice::Context& __ctx, const ::RoboCompTests::Callback_publishTest_msgTestPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_msgTest(id, &__ctx, __del, __cookie);
    }

    void end_msgTest(const ::Ice::AsyncResultPtr&);
    
private:

    void msgTest(::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_msgTest(::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<publishTest> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_secure(bool __secure) const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_twoway() const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_oneway() const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_batchOneway() const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_datagram() const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_batchDatagram() const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_compress(bool __compress) const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_timeout(int __timeout) const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<publishTest> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<publishTest*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace RoboCompTests
{

class test : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void printmsg(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

class serviceTest : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void srvTest(::Ice::Int, ::Ice::Int&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

class publishTest : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void msgTest(::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace RoboCompTests
{

class test : virtual public ::IceDelegate::RoboCompTests::test,
             virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void printmsg(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

class serviceTest : virtual public ::IceDelegate::RoboCompTests::serviceTest,
                    virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void srvTest(::Ice::Int, ::Ice::Int&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

class publishTest : virtual public ::IceDelegate::RoboCompTests::publishTest,
                    virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void msgTest(::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace RoboCompTests
{

class test : virtual public ::IceDelegate::RoboCompTests::test,
             virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void printmsg(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

class serviceTest : virtual public ::IceDelegate::RoboCompTests::serviceTest,
                    virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void srvTest(::Ice::Int, ::Ice::Int&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

class publishTest : virtual public ::IceDelegate::RoboCompTests::publishTest,
                    virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void msgTest(::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace RoboCompTests
{

class test : virtual public ::Ice::Object
{
public:

    typedef testPrx ProxyType;
    typedef testPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void printmsg(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___printmsg(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const test& l, const test& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const test& l, const test& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

class serviceTest : virtual public ::Ice::Object
{
public:

    typedef serviceTestPrx ProxyType;
    typedef serviceTestPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void srvTest(::Ice::Int, ::Ice::Int&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___srvTest(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const serviceTest& l, const serviceTest& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const serviceTest& l, const serviceTest& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

class publishTest : virtual public ::Ice::Object
{
public:

    typedef publishTestPrx ProxyType;
    typedef publishTestPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void msgTest(::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___msgTest(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const publishTest& l, const publishTest& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const publishTest& l, const publishTest& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace RoboCompTests
{

template<class T>
class CallbackNC_test_printmsg : public Callback_test_printmsg_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_test_printmsg(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_test_printmsgPtr
newCallback_test_printmsg(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_test_printmsg<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_test_printmsgPtr
newCallback_test_printmsg(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_test_printmsg<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_test_printmsgPtr
newCallback_test_printmsg(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_test_printmsg<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_test_printmsgPtr
newCallback_test_printmsg(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_test_printmsg<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_test_printmsg : public Callback_test_printmsg_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_test_printmsg(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_test_printmsgPtr
newCallback_test_printmsg(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_test_printmsg<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_test_printmsgPtr
newCallback_test_printmsg(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_test_printmsg<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_test_printmsgPtr
newCallback_test_printmsg(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_test_printmsg<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_test_printmsgPtr
newCallback_test_printmsg(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_test_printmsg<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_serviceTest_srvTest : public Callback_serviceTest_srvTest_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_serviceTest_srvTest(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::RoboCompTests::serviceTestPrx __proxy = ::RoboCompTests::serviceTestPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int idTest;
        try
        {
            __proxy->end_srvTest(idTest, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(idTest);
        }
    }

    Response response;
};

template<class T> Callback_serviceTest_srvTestPtr
newCallback_serviceTest_srvTest(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_serviceTest_srvTest<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_serviceTest_srvTestPtr
newCallback_serviceTest_srvTest(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_serviceTest_srvTest<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_serviceTest_srvTest : public Callback_serviceTest_srvTest_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_serviceTest_srvTest(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::RoboCompTests::serviceTestPrx __proxy = ::RoboCompTests::serviceTestPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int idTest;
        try
        {
            __proxy->end_srvTest(idTest, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(idTest, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_serviceTest_srvTestPtr
newCallback_serviceTest_srvTest(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_serviceTest_srvTest<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_serviceTest_srvTestPtr
newCallback_serviceTest_srvTest(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_serviceTest_srvTest<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_publishTest_msgTest : public Callback_publishTest_msgTest_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_publishTest_msgTest(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_publishTest_msgTestPtr
newCallback_publishTest_msgTest(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_publishTest_msgTest<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_publishTest_msgTestPtr
newCallback_publishTest_msgTest(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_publishTest_msgTest<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_publishTest_msgTestPtr
newCallback_publishTest_msgTest(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_publishTest_msgTest<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_publishTest_msgTestPtr
newCallback_publishTest_msgTest(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_publishTest_msgTest<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_publishTest_msgTest : public Callback_publishTest_msgTest_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_publishTest_msgTest(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_publishTest_msgTestPtr
newCallback_publishTest_msgTest(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_publishTest_msgTest<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_publishTest_msgTestPtr
newCallback_publishTest_msgTest(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_publishTest_msgTest<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_publishTest_msgTestPtr
newCallback_publishTest_msgTest(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_publishTest_msgTest<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_publishTest_msgTestPtr
newCallback_publishTest_msgTest(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_publishTest_msgTest<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
