# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/h20/robocomp/tools/rcmanager/editorForm.ui'
#
# Created: Tue Aug 16 22:34:36 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(768, 539)
        self.table = QtGui.QTableWidget(Form)
        self.table.setGeometry(QtCore.QRect(4, 170, 761, 361))
        self.table.setObjectName(_fromUtf8("table"))
        self.table.setColumnCount(7)
        self.table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(650, 10, 111, 81))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.newButton = QtGui.QPushButton(self.groupBox_2)
        self.newButton.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.newButton.setObjectName(_fromUtf8("newButton"))
        self.deleteButton = QtGui.QPushButton(self.groupBox_2)
        self.deleteButton.setGeometry(QtCore.QRect(10, 45, 91, 21))
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(650, 90, 111, 71))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.readButton = QtGui.QPushButton(self.groupBox)
        self.readButton.setGeometry(QtCore.QRect(10, 18, 91, 21))
        self.readButton.setObjectName(_fromUtf8("readButton"))
        self.writeButton = QtGui.QPushButton(self.groupBox)
        self.writeButton.setGeometry(QtCore.QRect(10, 43, 91, 20))
        self.writeButton.setObjectName(_fromUtf8("writeButton"))
        self.frame = QtGui.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 641, 161))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.upLine = QtGui.QLineEdit(self.frame)
        self.upLine.setGeometry(QtCore.QRect(10, 80, 300, 25))
        self.upLine.setReadOnly(False)
        self.upLine.setObjectName(_fromUtf8("upLine"))
        self.pathButton = QtGui.QPushButton(self.frame)
        self.pathButton.setGeometry(QtCore.QRect(555, 30, 75, 25))
        self.pathButton.setObjectName(_fromUtf8("pathButton"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 56, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(330, 60, 121, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.downLine = QtGui.QLineEdit(self.frame)
        self.downLine.setGeometry(QtCore.QRect(330, 80, 300, 25))
        self.downLine.setReadOnly(False)
        self.downLine.setObjectName(_fromUtf8("downLine"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 121, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pathLine = QtGui.QLineEdit(self.frame)
        self.pathLine.setGeometry(QtCore.QRect(230, 30, 311, 25))
        self.pathLine.setReadOnly(False)
        self.pathLine.setObjectName(_fromUtf8("pathLine"))
        self.aliasLine = QtGui.QLineEdit(self.frame)
        self.aliasLine.setGeometry(QtCore.QRect(10, 30, 211, 25))
        self.aliasLine.setReadOnly(False)
        self.aliasLine.setObjectName(_fromUtf8("aliasLine"))
        self.endpointLine = QtGui.QLineEdit(self.frame)
        self.endpointLine.setGeometry(QtCore.QRect(220, 130, 190, 25))
        self.endpointLine.setReadOnly(False)
        self.endpointLine.setObjectName(_fromUtf8("endpointLine"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(220, 110, 56, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(230, 10, 56, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.dependencesLine = QtGui.QLineEdit(self.frame)
        self.dependencesLine.setGeometry(QtCore.QRect(10, 130, 200, 25))
        self.dependencesLine.setReadOnly(False)
        self.dependencesLine.setObjectName(_fromUtf8("dependencesLine"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 91, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.configLine = QtGui.QLineEdit(self.frame)
        self.configLine.setGeometry(QtCore.QRect(420, 130, 211, 25))
        self.configLine.setReadOnly(False)
        self.configLine.setObjectName(_fromUtf8("configLine"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(420, 110, 111, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "managerComp file editor", None))
        self.table.setSortingEnabled(False)
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Alias", None))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Deps", None))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Endpoint", None))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Path", None))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Up Command", None))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Down Command", None))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Config", None))
        self.groupBox_2.setTitle(_translate("Form", "Components", None))
        self.newButton.setText(_translate("Form", "New", None))
        self.deleteButton.setText(_translate("Form", "Delete", None))
        self.groupBox.setTitle(_translate("Form", "File", None))
        self.readButton.setText(_translate("Form", "Read", None))
        self.writeButton.setText(_translate("Form", "Write", None))
        self.pathButton.setText(_translate("Form", " browse", None))
        self.label_2.setText(_translate("Form", "Alias:", None))
        self.label_6.setText(_translate("Form", "Down Command:", None))
        self.label_5.setText(_translate("Form", "Up Command:", None))
        self.label_3.setText(_translate("Form", "Endpoint", None))
        self.label_4.setText(_translate("Form", "Path:", None))
        self.label_7.setText(_translate("Form", "Dependences", None))
        self.label_8.setText(_translate("Form", "Configuration file", None))

