# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pbustos/robocomp/tools/rcmanager/editorForm.ui'
#
# Created: Sat Nov 10 19:37:51 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(768, 539)
        self.table = QtGui.QTableWidget(Form)
        self.table.setGeometry(QtCore.QRect(4, 170, 761, 361))
        self.table.setObjectName("table")
        self.table.setColumnCount(7)
        self.table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(650, 10, 111, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.newButton = QtGui.QPushButton(self.groupBox_2)
        self.newButton.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.newButton.setObjectName("newButton")
        self.deleteButton = QtGui.QPushButton(self.groupBox_2)
        self.deleteButton.setGeometry(QtCore.QRect(10, 45, 91, 21))
        self.deleteButton.setObjectName("deleteButton")
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(650, 90, 111, 71))
        self.groupBox.setObjectName("groupBox")
        self.readButton = QtGui.QPushButton(self.groupBox)
        self.readButton.setGeometry(QtCore.QRect(10, 18, 91, 21))
        self.readButton.setObjectName("readButton")
        self.writeButton = QtGui.QPushButton(self.groupBox)
        self.writeButton.setGeometry(QtCore.QRect(10, 43, 91, 20))
        self.writeButton.setObjectName("writeButton")
        self.frame = QtGui.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 641, 161))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.upLine = QtGui.QLineEdit(self.frame)
        self.upLine.setGeometry(QtCore.QRect(10, 80, 300, 25))
        self.upLine.setReadOnly(False)
        self.upLine.setObjectName("upLine")
        self.pathButton = QtGui.QPushButton(self.frame)
        self.pathButton.setGeometry(QtCore.QRect(555, 30, 75, 25))
        self.pathButton.setObjectName("pathButton")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 56, 17))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(330, 60, 121, 17))
        self.label_6.setObjectName("label_6")
        self.downLine = QtGui.QLineEdit(self.frame)
        self.downLine.setGeometry(QtCore.QRect(330, 80, 300, 25))
        self.downLine.setReadOnly(False)
        self.downLine.setObjectName("downLine")
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 121, 17))
        self.label_5.setObjectName("label_5")
        self.pathLine = QtGui.QLineEdit(self.frame)
        self.pathLine.setGeometry(QtCore.QRect(230, 30, 311, 25))
        self.pathLine.setReadOnly(False)
        self.pathLine.setObjectName("pathLine")
        self.aliasLine = QtGui.QLineEdit(self.frame)
        self.aliasLine.setGeometry(QtCore.QRect(10, 30, 211, 25))
        self.aliasLine.setReadOnly(False)
        self.aliasLine.setObjectName("aliasLine")
        self.endpointLine = QtGui.QLineEdit(self.frame)
        self.endpointLine.setGeometry(QtCore.QRect(220, 130, 190, 25))
        self.endpointLine.setReadOnly(False)
        self.endpointLine.setObjectName("endpointLine")
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(220, 110, 56, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(230, 10, 56, 17))
        self.label_4.setObjectName("label_4")
        self.dependencesLine = QtGui.QLineEdit(self.frame)
        self.dependencesLine.setGeometry(QtCore.QRect(10, 130, 200, 25))
        self.dependencesLine.setReadOnly(False)
        self.dependencesLine.setObjectName("dependencesLine")
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 91, 21))
        self.label_7.setObjectName("label_7")
        self.configLine = QtGui.QLineEdit(self.frame)
        self.configLine.setGeometry(QtCore.QRect(420, 130, 211, 25))
        self.configLine.setReadOnly(False)
        self.configLine.setObjectName("configLine")
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(420, 110, 111, 21))
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "managerComp file editor", None, QtGui.QApplication.UnicodeUTF8))
        self.table.setSortingEnabled(False)
        self.table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Alias", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Deps", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "Endpoint", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "Up Command", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "Down Command", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Form", "Config", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Components", None, QtGui.QApplication.UnicodeUTF8))
        self.newButton.setText(QtGui.QApplication.translate("Form", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setText(QtGui.QApplication.translate("Form", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.readButton.setText(QtGui.QApplication.translate("Form", "Read", None, QtGui.QApplication.UnicodeUTF8))
        self.writeButton.setText(QtGui.QApplication.translate("Form", "Write", None, QtGui.QApplication.UnicodeUTF8))
        self.pathButton.setText(QtGui.QApplication.translate("Form", " browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Alias:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Down Command:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Up Command:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Endpoint", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Dependences", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Configuration file", None, QtGui.QApplication.UnicodeUTF8))

