#!/bin/bash
set -e
user="$(users| awk '{print $1;}')"
sudo sed -i "/\/opt\/robocomp\/lib/d" /etc/ld.so.conf
sudo ldconfig
sed -i "/export ROBOCOMP=/d" /home/$user/.bashrc
sed -i "/export PATH=\$PATH:\/opt\/robocomp\/bin/d" /home/$user/.bashrc
source ~/.bashrc
