#!/bin/bash
set -e
user="$(users| awk '{print $1;}')"
sudo sed -i "/\/opt\/robocomp\/lib/d" /etc/ld.so.conf
sudo ldconfig
sudo sed -i "/source \/opt\/robocomp\/share\/setup/d" /home/$user/.bashrc
source /home/$user/.bashrc
