#!/bin/bash
set -e
user="$(users| awk '{print $1;}')"
echo "export ROBOCOMP=/home/$user/robocomp" >> /home/$user/.bashrc
echo 'export PATH=$PATH:/opt/robocomp/bin' >> /home/$user/.bashrc
source /home/$user/.bashrc
