//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: AGMAgent.idl
//  Source: AGMAgent.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPAGMAGENT_ICE
#define ROBOCOMPAGMAGENT_ICE

#include <AGMWorldModel.ice>

module RoboCompAGMAgent{

	interface AGMAgentTopic{
		void  modificationProposal(RoboCompAGMWorldModel::Event modification);
		void  update(RoboCompAGMWorldModel::Node nodeModification);
	};
};
  
#endif