//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: AprilTags.idl
//  Source: AprilTags.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPAPRILTAGS_ICE
#define ROBOCOMPAPRILTAGS_ICE

module RoboCompAprilTags{

	interface AprilTags{
		void  newAprilTag(int id, float tx, float ty, float tz, float rx, float ry, float rz);
	};
};
  
#endif