//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: Ar.idl
//  Source: Ar.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPAR_ICE
#define ROBOCOMPAR_ICE

module RoboCompAr{

	interface Ar{
	};
};
  
#endif