//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: ASRComprehension.idl
//  Source: ASRComprehension.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPASRCOMPREHENSION_ICE
#define ROBOCOMPASRCOMPREHENSION_ICE

module RoboCompASRComprehension{

	interface ASRComprehension{
		void  mode(string text);
	};
};
  
#endif