//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: CGR.idl
//  Source: CGR.idsl
//  
//******************************************************************   
#ifndef CGR_ICE
#define CGR_ICE

module CGR{
	
	interface CGR{
		void  newCGRPose(float x, float z, float alpha);
	};
};
  
#endif