//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: Cognitive.idl
//  Source: Cognitive.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPCOGNITIVE_ICE
#define ROBOCOMPCOGNITIVE_ICE

module RoboCompCognitive{

	interface Cognitive{
	};
};
  
#endif