//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: Conversational.idl
//  Source: Conversational.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPCONVERSATIONAL_ICE
#define ROBOCOMPCONVERSATIONAL_ICE

module RoboCompConversational{

	interface Conversational{
		void  start();
		void  stop();
		void  sayHello();
	};
};
  
#endif