//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: DialogManager.idl
//  Source: DialogManager.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPDIALOGMANAGER_ICE
#define ROBOCOMPDIALOGMANAGER_ICE

module RoboCompDialogManager{

	interface DialogManager{
	};
};
  
#endif