//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: DSRGetID.ice
//  Source: DSRGetID.idsl
//  
//****************************************************************** 
#ifndef ROBOCOMPDSRGETID_ICE
#define ROBOCOMPDSRGETID_ICE
module RoboCompDSRGetID
{
	interface DSRGetID
	{
		int getID ();
	};
};

#endif
