//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: FaceRecognitionTrain.idl
//  Source: FaceRecognitionTrain.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPFACERECOGNITIONTRAIN_ICE
#define ROBOCOMPFACERECOGNITIONTRAIN_ICE

module RoboCompFaceRecognitionTrain{

	interface FaceRecognitionTrain{
	};
};
  
#endif