//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: Fovis.idl
//  Source: Fovis.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPFOVIS_ICE
#define ROBOCOMPFOVIS_ICE

module RoboCompFovis{

	interface Fovis{
		void  currentPose(out float tx, out float tz, out float alfa);
	};
};
  
#endif