//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: GsocTest03.idl
//  Source: GsocTest03.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPGSOCTEST03_ICE
#define ROBOCOMPGSOCTEST03_ICE

module RoboCompGsocTest03{

	interface GsocTest03{
		void  setNumDoStuff(int result);
	};
};
  
#endif