//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: IkPuma.idl
//  Source: IkPuma.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPIKPUMA_ICE
#define ROBOCOMPIKPUMA_ICE

#include <CommonHead.ice>

module RoboCompIkPuma{

	interface IkPuma{
		void  setPosition(int x, int y, int z);
	};
};
  
#endif