//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: multimodal.idl
//  Source: multimodal.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPMULTIMODAL_ICE
#define ROBOCOMPMULTIMODAL_ICE

module RoboCompmultimodal{

	interface multimodal{
	};
};
  
#endif