//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: objectDetection.idl
//  Source: objectDetection.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPOBJECTDETECTION_ICE
#define ROBOCOMPOBJECTDETECTION_ICE

module RoboCompobjectDetection{

	interface objectDetection{
		void  setModel2Fit(string model);
		void  removePCwithinModel(string model);
	};
};
  
#endif