//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: Persona.idl
//  Source: Persona.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPPERSONA_ICE
#define ROBOCOMPPERSONA_ICE

module RoboCompPersona{

	interface Persona{
	};
};
  
#endif