//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: objectDetection.idl
//  Source: objectDetection.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPOBJECTDETECTION_ICE
#define ROBOCOMPOBJECTDETECTION_ICE

module RoboCompSemanticSimilarity
{

	interface SemanticSimilarity 
        {
		void w2vDistance(string word1, string word2, out float result);
	};
};
  
#endif
