//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: Sevilla2.idl
//  Source: Sevilla2.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPSEVILLA2_ICE
#define ROBOCOMPSEVILLA2_ICE

module RoboCompSevilla2{

	interface Sevilla2{
	};
};
  
#endif