//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: SimDemoBalls.idl
//  Source: SimDemoBalls.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPSIMDEMOBALLS_ICE
#define ROBOCOMPSIMDEMOBALLS_ICE

module RoboCompSimDemoBalls{

	interface SimDemoBalls{
		void  newText(string command);
	};
};
  
#endif