//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: Trajectory2.idl
//  Source: Trajectory2.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPTRAJECTORY2_ICE
#define ROBOCOMPTRAJECTORY2_ICE

module RoboCompTrajectory2{

	interface Trajectory2{
	};
};
  
#endif