//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: TrajectoryRobot2D.idl
//  Source: TrajectoryRobot2D.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPTRAJECTORYROBOT2D_ICE
#define ROBOCOMPTRAJECTORYROBOT2D_ICE

module RoboCompTrajectoryRobot2D{
	exception RoboCompException{string text;};
	["cpp:comparable"]
	struct TargetPose{
		bool doRotation;
		float x;
					float y;
					float z;
					float rx;
					float ry;
					float rz;
				};
	["cpp:comparable"]
	struct NavState{
		long elapsedTime;
		long estimatedTime;
		long planningTime;
		string state;
	};

	interface TrajectoryRobot2D{
		void  go(TargetPose target)throws RoboCompException;
		void  goBackwards(TargetPose target)throws RoboCompException;
		void  changeTarget(TargetPose target)throws RoboCompException;
		NavState getState();
		void  stop();
	};
};
  
#endif