//******************************************************************
// 
//  Generated by IDSL to IDL Translator
//  
//  File name: UrsusNeck.idl
//  Source: UrsusNeck.idsl
//  
//******************************************************************   
#ifndef ROBOCOMPURSUSNECK_ICE
#define ROBOCOMPURSUSNECK_ICE

module RoboCompUrsusNeck{

	interface UrsusNeck{
		void setMouth(float pos);
	};
};
  
#endif