IF( "$ENV{CAFFEROOT}" STREQUAL "" )
  MESSAGE(STATUS "CAFFEROOT environment variable not set." )
  MESSAGE(STATUS "This can be done in your user .bashrc file by appending the corresponding line, e.g:" )
  MESSAGE(STATUS "export CAFFEROOT=/usr/local/" )
  SET(CAFFE_FOUND 0)
ELSE( "$ENV{CAFFEROOT}" STREQUAL "" )
  MESSAGE(STATUS "CAFFEROOT environment variable set. Using specific driver...:wq" )
  SET(CAFFE_LIBS -lcaffe)
  INCLUDE_DIRECTORIES( "$ENV{CAFFEROOT}/include/")
  SET( LIBS ${LIBS} ${CAFFE_LIBS} -L$ENV{CAFFEROOT}/lib/ )
  ADD_DEFINITIONS(-DCOMPILE_CAFFE=1)
  SET(CAFFE_FOUND 1)
  SET (LIBS ${LIBS} ${CAFFE_LIBS})
ENDIF( "$ENV{CAFFEROOT}" STREQUAL "" )
