IF( "$ENV{DYNAMIXELROOT}" STREQUAL "" )
  MESSAGE(STATUS "DYNAMIXELROOT environment variable not set." )
  MESSAGE(STATUS "This can be done in your user .bashrc file by appending the corresponding line, e.g:" )
  MESSAGE(STATUS "export DYNAMIXELROOT=/usr/local/" )
  SET(DYNAMIXEL_FOUND 0)
ELSE( "$ENV{DYNAMIXELROOT}" STREQUAL "" )
  MESSAGE(STATUS "DYNAMIXELROOT environment variable set. Using specific driver...:wq" )
  SET(DYNAMIXEL_LIBS -ldxl)
  INCLUDE_DIRECTORIES( "$ENV{DYNAMIXELROOT}/include/")
  SET( LIBS ${LIBS} ${DYNAMIXEL_LIBS} -L$ENV{DYNAMIXELROOT}/lib/ )
  ADD_DEFINITIONS(-DCOMPILE_DYNAMIXEL=1)
  SET(DYNAMIXEL_FOUND 1)
  SET (LIBS ${LIBS} ${DYNAMIXEL_LIBS})
ENDIF( "$ENV{DYNAMIXELROOT}" STREQUAL "" )
