IF( "$ENV{FAULHABERROOT}" STREQUAL "" )
  MESSAGE(STATUS "FAULHABERROOT environment variable not set." )
  MESSAGE(STATUS "This can be done in your user .bashrc file by appending the corresponding line, e.g:" )
  MESSAGE(STATUS "export FAULHABERROOT=/usr/local/" )
  MESSAGE(STATUS "FAULHABERROOT environment variable not set." )
  MESSAGE(STATUS "")
  MESSAGE(STATUS "FAULHABERROOT environment variable not set." )
  MESSAGE(STATUS "")
  MESSAGE(STATUS "FAULHABERROOT environment variable not set." )
  MESSAGE(STATUS "")
  MESSAGE(FATAL_ERROR "FAULHABERROOT environment variable not set." )

  SET(FAULHABER_FOUND 0)
ELSE( "$ENV{FAULHABERROOT}" STREQUAL "" )
  SET(FAULHABER_LIBS -lvs_can_api)
  INCLUDE_DIRECTORIES( "$ENV{FAULHABERROOT}/include/")
  SET( LIBS ${LIBS} ${FAULHABER_LIBS} -L$ENV{FAULHABERROOT}/lib/ )
  ADD_DEFINITIONS(-DCOMPILE_FAULHABER=1)
  SET(FAULHABER_FOUND 1)
  SET (LIBS ${LIBS} ${FAULHABER_LIBS})
ENDIF( "$ENV{FAULHABERROOT}" STREQUAL "" )
