# Point Cloud Library
FIND_PACKAGE( PCL 1.7 REQUIRED )

LIST( APPEND CMAKE_MODULE_PATH $ENV{ROBOCOMP}/cmake/modules )

INCLUDE_DIRECTORIES( ${PCL_INCLUDE_DIRS} )
LINK_DIRECTORIES( ${PCL_LIBRARY_DIRS} )
ADD_DEFINITIONS( ${PCL_DEFINITIONS} )
 
INCLUDE_DIRECTORIES( ${PCL_INCLUDE_DIRS} )

MESSAGE("X X X X X X X X X X X ${PCL_INCLUDE_DIRS} ${PCL_LIBRARY_DIRS}  ")

SET( LIBS ${LIBS} ${PCL_LIBRARY_DIRS}  ${PCL_LIBRARIES}  )
message("PCL libraries: ${LIBS}" )
