IF( "$ENV{PROSILICAROOT}" STREQUAL "" )
  MESSAGE(STATUS "PROSILICAROOT environment variable not set." )
  MESSAGE(STATUS "This can be done in your user .bashrc file by appending the corresponding line, e.g:" )
  MESSAGE(STATUS "export PROSILICAROOT=/usr/local/" )
  MESSAGE(STATUS "You can download the Prosilica SDK from http://www.alliedvisiontec.com/fileadmin/content/PDF/Software/Prosilica_software/Prosilica_SDK/AVT_GigE_SDK_1.2.22_Linux.tar.gz")
  SET(PROSILICA_FOUND 0)
ELSE( "$ENV{PROSILICAROOT}" STREQUAL "" )
  SET(PROSILICA_LIBS -lPvAPI)
  INCLUDE_DIRECTORIES( "$ENV{PROSILICAROOT}/inc-pc/")
  IF( $ENV{IPPROOT} MATCHES .*[6][4].*)
    SET( LIBS ${LIBS} ${PROSILICA_LIBS} -L$ENV{PROSILICAROOT}/bin-pc/x64/ )
	ADD_DEFINITIONS(-D_x64=1)
  ELSE( $ENV{IPPROOT} MATCHES .*[6][4].*)
    SET( LIBS ${LIBS} ${PROSILICA_LIBS} -L$ENV{PROSILICAROOT}/bin-pc/x86/ )
	ADD_DEFINITIONS(-D_x86=1)
  ENDIF( $ENV{IPPROOT} MATCHES .*[6][4].*)
  ADD_DEFINITIONS(-DCOMPILE_PROSILICA=1)
  ADD_DEFINITIONS(-D_LINUX=1)
  SET(PROSILICA_FOUND 1)
  SET (LIBS ${LIBS} ${PROSILICA_LIBS})
ENDIF( "$ENV{PROSILICAROOT}" STREQUAL "" )

