#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys, traceback
sys.path.append('/usr/local/share/agm')

from AGGL import *
from parseAGGL import *
from pddlAGGL import *

ret = 0
try:
	ok = True
	if len(sys.argv)==7:
		if sys.argv[1] != '-i':
			ok = False
		if sys.argv[3] != '-a':
			ok = False
		if sys.argv[5] != '-f':
			ok = False
		if ok:
			inputFile         = sys.argv[2]
			outputFilePartial = sys.argv[4]
			outputFileFull    = sys.argv[6]
			agmData = AGMFileDataParsing.fromFile(inputFile)
			agmData.generatePDDL(outputFileFull, skipPassiveRules=False)
			agmData.generatePDDL(outputFilePartial, skipPassiveRules=True)
	else:
		ok = False

	if not ok:
		print '\n'+sys.argv[0], ' -i <inputFile.aggl> -a <activeRules.pddl> -f <activeAndPassiveRules.pddl>\n'
		ret = 1
except:
	print 'Error'
	traceback.print_exc(file=sys.stdout)
	ret = -1
	
sys.exit(ret)
