//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `Logger.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Logger.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompLogger_Logger_ids[2] =
{
    "::Ice::Object",
    "::RoboCompLogger::Logger"
};
const ::std::string iceC_RoboCompLogger_Logger_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sendMessage"
};
const ::std::string iceC_RoboCompLogger_Logger_sendMessage_name = "sendMessage";

}

bool
RoboCompLogger::Logger::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompLogger_Logger_ids, iceC_RoboCompLogger_Logger_ids + 2, s);
}

::std::vector<::std::string>
RoboCompLogger::Logger::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompLogger_Logger_ids[0], &iceC_RoboCompLogger_Logger_ids[2]);
}

::std::string
RoboCompLogger::Logger::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompLogger::Logger::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompLogger::Logger";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompLogger::Logger::_iceD_sendMessage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    LogMessage iceP_m;
    istr->readAll(iceP_m);
    inS.endReadParams();
    this->sendMessage(::std::move(iceP_m), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompLogger::Logger::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompLogger_Logger_ops, iceC_RoboCompLogger_Logger_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompLogger_Logger_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_sendMessage(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompLogger::LoggerPrx::_iceI_sendMessage(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const LogMessage& iceP_m, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompLogger_Logger_sendMessage_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_m);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompLogger::LoggerPrx::_newInstance() const
{
    return ::IceInternal::createProxy<LoggerPrx>();
}
/// \endcond

const ::std::string&
RoboCompLogger::LoggerPrx::ice_staticId()
{
    return Logger::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompLogger_Logger_sendMessage_name = "sendMessage";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompLogger::upCast(Logger* p) { return p; }

void
::IceProxy::RoboCompLogger::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< Logger>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new Logger;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompLogger::Logger::_iceI_begin_sendMessage(const ::RoboCompLogger::LogMessage& iceP_m, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompLogger_Logger_sendMessage_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompLogger_Logger_sendMessage_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_m);
        result->endWriteParams();
        result->invoke(iceC_RoboCompLogger_Logger_sendMessage_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompLogger::Logger::end_sendMessage(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompLogger_Logger_sendMessage_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompLogger::Logger::_newInstance() const
{
    return new Logger;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompLogger::Logger::ice_staticId()
{
    return ::RoboCompLogger::Logger::ice_staticId();
}

RoboCompLogger::Logger::~Logger()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompLogger::upCast(Logger* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompLogger_Logger_ids[2] =
{
    "::Ice::Object",
    "::RoboCompLogger::Logger"
};

}

bool
RoboCompLogger::Logger::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompLogger_Logger_ids, iceC_RoboCompLogger_Logger_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompLogger::Logger::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompLogger_Logger_ids[0], &iceC_RoboCompLogger_Logger_ids[2]);
}

const ::std::string&
RoboCompLogger::Logger::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompLogger::Logger::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompLogger::Logger";
    return typeId;
#else
    return iceC_RoboCompLogger_Logger_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompLogger::Logger::_iceD_sendMessage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    LogMessage iceP_m;
    istr->read(iceP_m);
    inS.endReadParams();
    this->sendMessage(iceP_m, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompLogger_Logger_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sendMessage"
};

}

/// \cond INTERNAL
bool
RoboCompLogger::Logger::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompLogger_Logger_all, iceC_RoboCompLogger_Logger_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompLogger_Logger_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_sendMessage(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompLogger::Logger::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< Logger, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompLogger::Logger::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< Logger, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompLogger::_icePatchObjectPtr(LoggerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = LoggerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(Logger::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
