IF( "$ENV{DUNKERROOT}" STREQUAL "" )
  MESSAGE(STATUS "DUNKERROOT environment variable not set." )
  MESSAGE(STATUS "This can be done in your user .bashrc file by appending the corresponding line, e.g:" )
  MESSAGE(STATUS "export DUNKERROOT=/usr/local/" )
  SET(DUNKER_FOUND 0)
ELSE( "$ENV{DUNKERROOT}" STREQUAL "" )
  SET(DUNKER_LIBS -lvs_can_api)
  INCLUDE_DIRECTORIES( "$ENV{DUNKERROOT}/include/")
  SET( LIBS ${LIBS} ${DUNKER_LIBS} -L$ENV{DUNKERROOT}/lib/ )
  ADD_DEFINITIONS(-DCOMPILE_DUNKER=1)
  SET(DUNKER_FOUND 1)
  SET (LIBS ${LIBS} ${DUNKER_LIBS})
ENDIF( "$ENV{DUNKERROOT}" STREQUAL "" )
