IF( "$ENV{GAZEBOROOT}" STREQUAL "" )
  MESSAGE(STATUS "GAZEBOROOT environment variable not set." )
  MESSAGE(STATUS "This can be done in your user .bashrc file by appending the corresponding line, e.g:" )
  MESSAGE(STATUS "export GAZEBOROOT=/usr/local/" )
  SET(GAZEBO_FOUND 0)
ELSE( "$ENV{GAZEBOROOT}" STREQUAL "" )
  SET(GAZEBO_LIBS -lgazebo)
  INCLUDE_DIRECTORIES( "$ENV{GAZEBOROOT}/include/")
  SET( LIBS ${LIBS} ${GAZEBO_LIBS} -L$ENV{GAZEBOROOT}/lib/ )
  ADD_DEFINITIONS(-DCOMPILE_GAZEBO=1)
  SET(GAZEBO_FOUND 1)
  SET (LIBS ${LIBS} ${GAZEBO_LIBS})
ENDIF( "$ENV{GAZEBOROOT}" STREQUAL "" )

