SET(GMAPPING_FOUND 0)

MACRO( GMAPPING_SET_VARIABLES)
  IF( "${GMAPPING_CONFIGURED}" STREQUAL "1" )
  ELSE( "${GMAPPING_CONFIGURED}" STREQUAL "1" )
    MESSAGE(STATUS "configuring gmapping")
    SET(GMAPPING_LIBS -lutils -lsensor_range -llog -lgridfastslam -lpthread -lconfigfile  -lsensor_base -lscanmatcher )
    ADD_DEFINITIONS(-DCOMPILE_GMAPPING=1)
    ADD_DEFINITIONS(-DUSE_GMAPPING=1)
    ADD_DEFINITIONS(-DGMAPPING_FOUND=1)
    INCLUDE_DIRECTORIES($ENV{GMAPPINGROOT} $ENV{GMAPPINGROOT}/include/ $ENV{GMAPPINGROOT}/configfile/ $ENV{GMAPPINGROOT}/grid/ $ENV{GMAPPINGROOT}/sensor/ $ENV{GMAPPINGROOT}/gridfastslam/ $ENV{GMAPPINGROOT}/particlefilter/ $ENV{GMAPPINGROOT}/scanmatcher/ $ENV{GMAPPINGROOT}/utils/ $ENV{GMAPPINGROOT}/log/  $ENV{GMAPPINGROOT}/gui/ )
    SET( LIBS ${LIBS} ${GMAPPING_LIBS} -L$ENV{GMAPPINGROOT}/sharedlib/ -L$ENV{GMAPPINGROOT}/lib/ )
    SET(GMAPPING_CONFIGURED 1)
  ENDIF( "${GMAPPING_CONFIGURED}" STREQUAL "1" )
ENDMACRO( GMAPPING_SET_VARIABLES)

MESSAGE(STATUS "REMEMBER TO INCLUDE \$ENV{GMAPPINGROOT}/lib IN /etc/ld.so.conf (and run 'sudo ldconfig' aferwards) or in your $LD_LIBRARY_PATH." )
IF( "$ENV{GMAPPINGROOT}" STREQUAL "" )
  MESSAGE(STATUS "GMAPPINGROOT environment variable not set." )
  MESSAGE(STATUS "This can be done in your user .bashrc file by appending the corresponding line, e.g:" )
  MESSAGE(STATUS "export GMAPPINGROOT=/usr/local/" )
  SET(GMAPPING_FOUND 0)
ELSE( "$ENV{GMAPPINGROOT}" STREQUAL "" )
  GMAPPING_SET_VARIABLES()
  SET(GMAPPING_FOUND 1)
ENDIF( "$ENV{GMAPPINGROOT}" STREQUAL "" )



