IF( "$ENV{ROSROOT}" STREQUAL "" )
  MESSAGE(STATUS "ROSROOT environment variable not set." )
  MESSAGE(STATUS "This can be done in your user .bashrc file by appending the corresponding line, e.g:" )
  MESSAGE(STATUS "export ROSROOT=/opt/ros/boxturtle/ros" )
  SET(ROS_FOUND 0)
ELSE( "$ENV{ROSROOT}" STREQUAL "" )
  SET(ROS_LIBS -lroslib -lros)
  INCLUDE_DIRECTORIES( "$ENV{ROSROOT}/ros_comm/clients/cpp/roscpp/include/")
  INCLUDE_DIRECTORIES( "$ENV{ROSROOT}/ros_comm/utilities/rostime/include/")
  INCLUDE_DIRECTORIES( "$ENV{ROSROOT}/ros_comm/utilities/cpp_common/include/")
  INCLUDE_DIRECTORIES( "$ENV{ROSROOT}/ros_comm/tools/rosconsole/include/")
  INCLUDE_DIRECTORIES( "$ENV{ROSROOT}/ros_comm/clients/cpp/roscpp_serialization/include/")
  INCLUDE_DIRECTORIES( "$ENV{ROSROOT}/ros_comm/clients/cpp/roscpp_traits/include/")
  INCLUDE_DIRECTORIES( "$ENV{ROSROOT}/ros_comm/utilities/xmlrpcpp/src/")
  SET( LIBS ${LIBS} ${ROS_LIBS} -L$ENV{ROSROOT}/ros/core/roslib/lib/ -L$ENV{ROSROOT}/ros_comm/clients/cpp/roscpp/lib/ )
  ADD_DEFINITIONS(-DCOMPILE_ROS=1)
  SET (ROS_FOUND 1)
  SET (LIBS ${LIBS} ${ROS_LIBS})
ENDIF( "$ENV{ROSROOT}" STREQUAL "" )


MACRO( ADD_ROS_MESSAGE_STACKS )
 FOREACH( input_file ${ARGN} )
    MESSAGE(STATUS "Adding directorie  $ENV{ROSROOT}/../stacks/${input_file}/msg/cpp/" )
    INCLUDE_DIRECTORIES("$ENV{ROSROOT}/../stacks/${input_file}/msg/cpp/" )
 ENDFOREACH( input_file )
ENDMACRO( ADD_ROS_MESSAGE_STACKS )
