IF( "$ENV{SCHUNKROOT}" STREQUAL "" )
  MESSAGE(STATUS "SCHUNKROOT environment variable not set." )
  MESSAGE(STATUS "This can be done in your user .bashrc file by appending the corresponding line, e.g:" )
  MESSAGE(STATUS "export SCHUNKROOT=/usr/local/" )
  SET(SCHUNK_FOUND 0)
ELSE( "$ENV{SCHUNKROOT}" STREQUAL "" )
  SET(SCHUNK_LIBS -lntcan )
  INCLUDE_DIRECTORIES( "$ENV{SCHUNKROOT}/include/")
  SET( LIBS ${LIBS} ${SCHUNK_LIBS} -L$ENV{SCHUNKROOT}/lib/ )
  ADD_DEFINITIONS(-DCOMPILE_SCHUNK=1)
  SET(SCHUNK_FOUND 1)
ENDIF( "$ENV{SCHUNKROOT}" STREQUAL "" )
