//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: FullPoseEstimationPub.ice
//  Source: FullPoseEstimationPub.idsl
//
//******************************************************************
#ifndef ROBOCOMPFULLPOSEESTIMATIONPUB_ICE
#define ROBOCOMPFULLPOSEESTIMATIONPUB_ICE
#include <FullPoseEstimation.ice>
module RoboCompFullPoseEstimationPub
{
	interface FullPoseEstimationPub
	{
		void newFullPose (RoboCompFullPoseEstimation::FullPoseEuler pose);
	};
};

#endif
