//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: FullPoseEstimation.ice
//  Source: FullPoseEstimation.idsl
//
//******************************************************************
#ifndef ROBOCOMPFULLPOSEESTIMATION_ICE
#define ROBOCOMPFULLPOSEESTIMATION_ICE
module RoboCompFullPoseEstimation
{
	exception HardwareFailedException{ string what; };
	struct FullPoseMatrix
	{
		string source;
		float m00;
		float m01;
		float m02;
		float m03;
		float m10;
		float m11;
		float m12;
		float m13;
		float m20;
		float m21;
		float m22;
		float m23;
		float m30;
		float m31;
		float m32;
		float m33;
	};
	struct FullPoseEuler
	{
		string source;
		float x;
		float y;
		float z;
		float rx;
		float ry;
		float rz;
		float vx;
		float vy;
		float vz;
		float vrx;
		float vry;
		float vrz;
		int confidence;
	};
	interface FullPoseEstimation
	{
		FullPoseEuler getFullPoseEuler ();
		FullPoseMatrix getFullPoseMatrix ();
		void setInitialPose (float x, float y, float z, float rx, float ry, float rz);
	};
};

#endif
